<figure>
<img src="../Imagenes/logo-final-ap.png"  width="80" height="80" align="left"/> 
</figure>

# <span style="color:blue"><left>Aprendizaje Profundo</left></span>

# <span style="color:red"><center>Visión por Computadora</center></span>
## <span style="color:red"><center>Introducción a OpenCV</center></span>

## <span style="color:blue">Contenido</span>

## <span style="color:blue">Prólogo</span>

OpenCV es la base y espina de los proyectos de visión artificial, por sus capacidades básicas de entrada y salida(I/O), hasta sus funciones complejas de transformaciones, procesamiento y deployment. Se comenzará el estudio de este paquete con la creación, lectura y procesamiento de imágenes

## <span style="color:blue">Prólogo</span>

OpenCV es la base y espina de los proyectos de visión artificial, por sus capacidades básicas de entrada y salida(I/O), hasta sus funciones complejas de transformaciones, procesamiento y deployment. Se comenzará el estudio de este paquete con la creación, lectura y procesamiento de imágenes

## <span style="color:blue">Lectura/Escritura de archivos de imagen</span>

OpenCV tiene dos funciones esenciales cuando se trabajan con imagenes fijas, y una que es buena de tener:

- `imread` para cargar una imagen desde un archivo
- `imwrite` para escribir una imagen a un archivo especificado
- `imshow` para mostrar la imágen en un cuadro

Aunque vamos a usar, principalmente OpenCV, es posible crear una imagen usando numPy

In [2]:
import numpy as np
import cv2

img = np.zeros((3,3), dtype = np.uint8)

print(img)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Acabamos de crear un cuadro negro de 3x3 pixeles. Lo importante es el argumento "dtype", el cual definimos como números enteros de 8 bits. Significa que tienen un rango de 0 a 255. 0 es negro y 255 es blanco, con el resto siendo rangos de gris. Cambiemos esto un poco

In [14]:
img2 = np.full((3, 3), 255, dtype = np.uint8) # cuadro 3x3 de color blanco
img3 = np.random.randint(0,255, (10,10),dtype = np.uint8) # cuadro 3x3 de colores aleatorios
print(img2)
print(img3)

[[255 255 255]
 [255 255 255]
 [255 255 255]]
[[200 198 190  21  12   4 249 172  13 145]
 [231 214 216  52  58  62 221 242  79 103]
 [ 63   9  99  72 112   8  40  48  17  89]
 [170 123 194 160  41  15 176  46 143  57]
 [246  95 187 164  10 179 131  18 106 191]
 [179  54 179 138 187 120 168 163  36   5]
 [ 46  49  75 147 236 161 247  54 239 253]
 [183  98  88 112 232  37 212   0  50 100]
 [253 200 246 250  44 100 203  49  49 146]
 [ 97  71  94 166 227 231 129  66 104 172]]


En este momento solo tenemos la idea "empirica" del color a partir de los números. Vamos a ver los números como colores 

In [15]:
cv2.imshow('black box',img) # pedimos que se abra una ventana con la imagen negra
cv2.imshow('white box',img2) # pedimos que se abra una ventana con la imagen blanca
cv2.imshow('random box',img3) # pedimos que se abra una ventana con la imagen aleatoria
cv2.waitKey(0) #le decimos que espere a continuar la interpretación del código hasta que se use una tecla
cv2.destroyAllWindows() # se cierran todas las ventanas creadas

guardemos la última imagen en formato `.png`

In [16]:
cv2.imwrite("../Imagenes/random_box.png", img3)

True